# Generated by Django 5.2.9 on 2025-12-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
