# Generated by Django 5.2.9 on 2025-12-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_nickname'),
        ('companies', '0004_companycomment_companycommentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='companies.company'),
        ),
    ]
