# Generated by Django 5.2.8 on 2025-11-14 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_code', models.CharField(max_length=10, unique=True)),
                ('corp_name', models.CharField(max_length=200)),
                ('ceo_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('corp_cls', models.CharField(blank=True, max_length=20, null=True)),
                ('corp_addr', models.CharField(blank=True, max_length=200, null=True)),
                ('stock_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ESGScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_score', models.FloatField(blank=True, null=True)),
                ('s_score', models.FloatField(blank=True, null=True)),
                ('g_score', models.FloatField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esg_score', to='companies.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.industry'),
        ),
    ]
